name: Build and Deploy to Github Pages
on:
    push:
        branches: 
        - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core 
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.300
        - name: Publish with dotnet
          run: dotnet publish ./src/QRCodeReaderWasm.sln --configuration Release --output build
        - name: Deploy to Github Pages
          uses: tranvuthien/github-pages-deploy-action
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BASE_BRANCH: master
            BRANCH: main
            FOLDER: build/wwwroot
            CLEAN: true
